import "../../layouts/carousel";
import "../../layouts/similar-companies";
import "../../layouts/similar-categories";
import "../../layouts/similar-locations";
import "../../scripts/tabs";
import "../../scripts/expand";
import "./map";
import "./brandsList";
import "./feedback";
